src/main/kotlin/apply/application/RecruitmentService.kt, src/main/kotlin/apply/domain/recruitment/Recruitment.kt, src/main/kotlin/apply/domain/recruitment/RecruitmentPeriod.kt, src/main/kotlin/apply/domain/recruitment/RecruitmentStatus.kt, src/main/kotlin/apply/ui/admin/RecruitmentView.kt, src/main/kotlin/support/Views.kt, src/test/kotlin/apply/domain/recruitment/RecruitmentStatusTest.kt
=> feat(recruitment): implement the recruitment management view

src/main/kotlin/apply/application/ApplicantService.kt, src/main/kotlin/apply/application/RecruitmentService.kt, src/main/kotlin/apply/domain/applicant/Applicant.kt, src/main/kotlin/apply/domain/applicant/ApplicantRepository.kt, src/main/kotlin/apply/domain/applicant/Gender.kt, src/main/kotlin/apply/ui/admin/BaseLayout.kt, src/main/kotlin/apply/ui/admin/SelectionView.kt, src/main/kotlin/apply/ui/admin/SelectionsView.kt, src/main/kotlin/support/Dates.kt, src/main/kotlin/support/Views.kt, src/test/kotlin/apply/domain/applicant/ApplicantRepositoryTest.kt
=> feat(selection) : implement selection management view

frontend/package-lock.json, frontend/src/api/recruitments.js, frontend/src/components/form/SummaryCheckField.vue, frontend/src/components/form/TextField.vue, frontend/src/components/form/TextInput.vue, frontend/src/router/index.js, frontend/src/utils/validation/regist.js, frontend/src/views/RecruitmentRegister.vue, frontend/vue.config.js, src/main/kotlin/apply/application/RecruitmentItemService.kt, src/main/kotlin/apply/domain/recruitmentitem/RecruitmentItem.kt, src/main/kotlin/apply/domain/recruitmentitem/RecruitmentItemRepository.kt, src/main/kotlin/apply/ui/api/RecruitmentRestController.kt, src/test/kotlin/apply/domain/recruitmentitem/RecruitmentItemRepositoryTest.kt
핀이 #56 pr에서 만들어놓은 컴포넌트들을 일단 먼저 가져다가 사용했습니다.
추후에 #56 pr이 머지되면 그 때 다시 리베이스 할게요!
기술 스택들이 전체적으로 익숙하지가 않아서 동작하는 코드를 위주로 짰습니다.
많은 피드백이 필요한 코드라, 눈에 보이는대로 피드백 주시면 정말 감사하겠습니다 🙇
=> feat(apply): implement the recruitment writing view

src/main/kotlin/apply/application/CheaterService.kt, src/main/kotlin/apply/domain/cheater/Cheater.kt, src/main/kotlin/apply/domain/cheater/CheaterRepository.kt, src/main/kotlin/apply/domain/cheater/CheaterResponse.kt, src/main/kotlin/apply/ui/admin/BaseLayout.kt, src/main/kotlin/apply/ui/admin/CheaterView.kt, src/test/kotlin/apply/domain/cheater/CheaterRepositoryTest.kt
merge commit 실수로 다시 PR 날립니다.
[이전 PR](https://github.com/woowacourse/service-apply/pull/73)
=> feat(cheater): implement the cheater view

frontend/src/components/form/BirthField.vue, frontend/src/components/form/GenderField.vue, frontend/src/components/form/RuleField.vue, frontend/src/components/form/TextField.vue, frontend/src/router/index.js, frontend/src/utils/validation/password.js, frontend/src/utils/validation/phoneNumber.js, frontend/src/utils/validation/register.js, frontend/src/views/ApplicationRegister.vue, frontend/src/views/Login.vue, frontend/src/views/PasswordFind.vue, frontend/src/views/Register.vue
Resolves #36, Resolves #37, Resolves #43 
submit button disable하드코딩 리뷰 받습니다.
=> feat(apply): implement password find view

src/main/kotlin/apply/application/ApplicantService.kt, src/main/kotlin/apply/domain/applicant/ApplicantResponse.kt, src/main/kotlin/apply/ui/admin/CheaterView.kt, src/main/kotlin/apply/ui/admin/SelectionView.kt, src/test/kotlin/apply/application/ApplicantServiceTest.kt, src/test/kotlin/apply/application/CheaterServiceTest.kt
=> feat(selection): add cheater column

build.gradle.kts, src/main/kotlin/apply/application/ApplicantService.kt, src/main/kotlin/apply/application/DownloadService.kt, src/main/kotlin/apply/ui/admin/SelectionView.kt, src/main/kotlin/apply/ui/admin/selections/SelectionView.kt, src/main/kotlin/apply/utils/ApplicantExcelRow.kt, src/main/kotlin/apply/utils/ExcelGenerator.kt, src/main/kotlin/apply/utils/ExcelRow.kt, src/main/kotlin/support/Properties.kt
코틀린을 사용했는데 자바 코드를 단순히 변환만 한 느낌이네요 😅
코틀린, 바딘 등 모든 부분에서 많은 피드백 부탁드립니다!
resolved: #26
=> feat(support): implement the excel download skeleton code

src/main/kotlin/apply/application/RecruitmentDtos.kt, src/main/kotlin/apply/application/RecruitmentService.kt, src/main/kotlin/apply/domain/recruitment/Recruitment.kt, src/main/kotlin/apply/domain/recruitment/RecruitmentPeriod.kt, src/main/kotlin/apply/domain/recruitment/RecruitmentRepository.kt, src/main/kotlin/apply/domain/recruitment/RecruitmentStatus.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentForm.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentsView.kt, src/main/kotlin/apply/ui/api/RecruitmentRestController.kt, src/main/kotlin/support/views/Components.kt, src/test/kotlin/apply/application/EvaluationServiceTest.kt, src/test/kotlin/apply/domain/recruitment/RecruitmentPeriodTest.kt, src/test/kotlin/apply/domain/recruitment/RecruitmentStatusTest.kt, src/test/kotlin/apply/ui/admin/recruitment/RecruitmentFormTest.kt
=> feat(recruitment): add new recruitment status

src/main/kotlin/apply/application/EvaluationService.kt, src/main/kotlin/apply/application/RecruitmentDtos.kt, src/main/kotlin/apply/application/RecruitmentService.kt, src/main/kotlin/apply/domain/recruitment/Recruitment.kt, src/main/kotlin/apply/domain/recruitmentitem/RecruitmentItem.kt, src/main/kotlin/apply/ui/admin/evaluation/EvaluationForm.kt, src/main/kotlin/apply/ui/admin/evaluation/EvaluationItemForm.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentForm.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentItemForm.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentsFormView.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentsView.kt, src/main/kotlin/apply/ui/api/RecruitmentRestController.kt, src/main/kotlin/support/domain/BaseEntity.kt, src/main/kotlin/support/views/BindingFormLayout.kt, src/main/kotlin/support/views/Buttons.kt, src/main/kotlin/support/views/Components.kt, src/main/kotlin/support/views/FormLayouts.kt, src/test/kotlin/apply/RecruitmentFixtures.kt, src/test/kotlin/apply/application/EvaluationServiceTest.kt, src/test/kotlin/apply/application/RecruitmentServiceTest.kt, src/test/kotlin/apply/ui/admin/recruitment/Fixtures.kt, src/test/kotlin/apply/ui/admin/recruitment/RecruitmentFormTest.kt, src/test/kotlin/apply/ui/admin/recruitment/RecruitmentItemFormTest.kt, src/test/kotlin/support/views/IdFieldTest.kt
=> feat(recruitment): implement the recruitment modify function

frontend/src/api/recruitments.js, frontend/src/components/ApplicationFormItem.vue, frontend/src/components/Box.vue, frontend/src/components/CommonItem.vue, frontend/src/components/RecruitItem.vue, frontend/src/views/MyApplications.vue, frontend/src/views/Recruits.vue
=> feat(apply): implement the recruits view

frontend/src/api/applicants.js, frontend/src/api/application-forms.js, frontend/src/api/recruitments.js, frontend/src/components/ApplicationFormItem.vue, frontend/src/components/RecruitItem.vue, frontend/src/router/index.js, frontend/src/views/ApplicantRegister.vue, frontend/src/views/ApplicationRegister.vue, frontend/src/views/Login.vue, frontend/src/views/Recruits.vue, src/main/kotlin/apply/application/ApplicationFormDtos.kt
=> refactor(apply): modify frontend url

frontend/src/App.vue, frontend/src/store/index.js, frontend/src/store/recruitments.js, frontend/src/views/ApplicationRegister.vue, frontend/src/views/Recruits.vue, src/main/kotlin/apply/application/RecruitmentService.kt
resolves #137
Recruitment를 전역으로 관리하게 되었습니다.
이런 UI입니다!
--------------------------------
수정했습니다!
=> feat(apply): add recruitment information to the application form

src/main/kotlin/apply/config/CorsConfig.kt
=> feat(system): add cors configuration

src/main/kotlin/apply/application/RecruitmentService.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentsView.kt
=> feat(recruitment): implement ended recruitment so that it can be modified

frontend/src/components/MainHeader.vue, frontend/src/components/form/Description.vue, frontend/src/components/form/TextField.vue, frontend/src/views/ApplicantRegister.vue, frontend/src/views/ApplicationRegister.vue, frontend/src/views/constants.js
=> fix(apply): improve the user experience

frontend/src/api/applicants.js, frontend/src/store/token.js, frontend/src/views/Login.vue, src/main/kotlin/apply/application/ApplicantDtos.kt, src/main/kotlin/apply/application/ApplicantService.kt, src/main/kotlin/apply/domain/applicant/ApplicantRepository.kt, src/test/kotlin/apply/application/ApplicantServiceTest.kt, src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
=> feat(applicant): remove the name and birthday from the applicant identification information

frontend/src/views/Login.vue, frontend/src/views/PasswordEdit.vue
=> feat(applicant): remove password format validation from my application view

frontend/src/views/ApplicationRegister.vue, src/main/kotlin/apply/application/ApplicationFormDtos.kt, src/main/kotlin/apply/application/ApplicationFormService.kt, src/main/kotlin/apply/domain/applicationform/ApplicationFormRepository.kt, src/test/kotlin/apply/RecruitmentFixtures.kt, src/test/kotlin/apply/application/ApplicationFormServiceTest.kt, src/test/kotlin/apply/domain/applicationform/ApplicationFormRepositoryTest.kt
=> feat(application): implement to submit only one application

frontend/src/components/Box.vue, frontend/src/components/RecruitCard.vue, frontend/src/components/form/Form.vue, frontend/src/components/form/TextInput.vue, frontend/src/views/ApplicantRegister.vue, frontend/src/views/ApplicationRegister.vue, frontend/src/views/Login.vue, frontend/src/views/PasswordEdit.vue, frontend/src/views/PasswordFind.vue, frontend/src/views/PasswordFindResult.vue
=> feat(apply): increase width of application form

src/main/kotlin/apply/application/RecruitmentDtos.kt, src/main/kotlin/apply/application/RecruitmentService.kt, src/main/kotlin/apply/domain/recruitment/Recruitment.kt, src/main/kotlin/apply/domain/recruitment/RecruitmentRepository.kt, src/main/kotlin/apply/domain/recruitment/RecruitmentStatus.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentForm.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentsView.kt, src/test/kotlin/apply/RecruitmentFixtures.kt, src/test/kotlin/apply/application/ApplicationFormServiceTest.kt, src/test/kotlin/apply/application/EvaluationServiceTest.kt, src/test/kotlin/apply/application/RecruitmentServiceTest.kt, src/test/kotlin/apply/domain/recruitment/RecruitmentStatusTest.kt, src/test/kotlin/apply/ui/admin/recruitment/RecruitmentFormTest.kt
=> refactor(recruitment): rename boolean variables to adjectives

src/main/kotlin/apply/application/ApplicantAuthenticationService.kt, src/main/kotlin/apply/application/ApplicantDtos.kt, src/main/kotlin/apply/application/ApplicantService.kt, src/main/kotlin/apply/application/ApplicantVerificationService.kt, src/main/kotlin/apply/application/EvaluationTargetService.kt, src/main/kotlin/apply/domain/applicant/Applicant.kt, src/main/kotlin/apply/domain/applicant/ApplicantAuthenticationException.kt, src/main/kotlin/apply/domain/applicant/ApplicantInformation.kt, src/main/kotlin/apply/domain/applicant/ApplicantRepository.kt, src/main/kotlin/apply/domain/applicant/ApplicantValidateException.kt, src/main/kotlin/apply/domain/applicant/Password.kt, src/main/kotlin/apply/ui/admin/cheater/CheatersView.kt, src/main/kotlin/apply/ui/admin/selections/SelectionView.kt, src/main/kotlin/apply/ui/api/ApplicantRestController.kt, src/main/kotlin/apply/ui/api/ExceptionHandler.kt, src/test/kotlin/apply/ApplicantFixtures.kt, src/test/kotlin/apply/ApplicationFormFixtures.kt, src/test/kotlin/apply/application/ApplicantAuthenticationServiceTest.kt, src/test/kotlin/apply/application/ApplicantServiceTest.kt, src/test/kotlin/apply/application/ApplicantVerificationServiceTest.kt, src/test/kotlin/apply/application/ApplicationFormServiceTest.kt, src/test/kotlin/apply/domain/applicant/ApplicantRepositoryTest.kt, src/test/kotlin/apply/domain/applicant/ApplicantTest.kt, src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
=> refactor(applicant): separate classes and structure tests

src/main/kotlin/apply/domain/applicant/Applicant.kt
=> fix(applicant): fix to not return null when calling getter

.gitignore, README.md, build.gradle.kts, docker/docker-compose.yml, src/main/kotlin/apply/domain/recruitmentitem/Answers.kt, src/main/resources/application-dev.properties, src/main/resources/application-local.properties, src/main/resources/application-test.properties, src/main/resources/application.properties, src/main/resources/db/migration/V1__Initialize_project_tables.sql, src/test/kotlin/apply/ApplicationTest.kt, src/test/kotlin/apply/application/ApplicantAuthenticationServiceTest.kt, src/test/kotlin/apply/application/ApplicantServiceTest.kt, src/test/kotlin/apply/application/ApplicationFormServiceTest.kt, src/test/kotlin/apply/application/EvaluationTargetServiceTest.kt, src/test/kotlin/apply/application/RecruitmentServiceTest.kt, src/test/kotlin/apply/domain/applicant/ApplicantRepositoryTest.kt, src/test/kotlin/apply/domain/applicationform/ApplicationFormRepositoryTest.kt, src/test/kotlin/apply/domain/cheater/CheaterRepositoryTest.kt, src/test/kotlin/apply/domain/evaluationitem/EvaluationItemRepositoryTest.kt, src/test/kotlin/apply/domain/evaluationtarget/EvaluationTargetRepositoryTest.kt, src/test/kotlin/apply/domain/recruitmentitem/RecruitmentItemRepositoryTest.kt, src/test/kotlin/apply/infra/mail/AwsMailSenderTest.kt, src/test/kotlin/apply/security/LoginApplicantResolverTest.kt, src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt, src/test/kotlin/apply/ui/api/ApplicationFormRestControllerTest.kt, src/test/kotlin/support/test/BaseTest.kt
=> feat(properties): separate properties

src/main/kotlin/apply/application/ApplicantService.kt
resolves #203 
지원자 기준으로 지원서를 matching하도록 하였습니다.
=> fix(selection): modify the list of applicants to be visible

src/main/kotlin/apply/application/ApplicationFormService.kt, src/main/kotlin/apply/domain/applicationform/ApplicationFormRepository.kt, src/main/kotlin/apply/ui/api/ApplicationFormRestController.kt, src/test/kotlin/apply/application/ApplicationFormServiceTest.kt, src/test/kotlin/apply/domain/applicationform/ApplicationFormTest.kt, src/test/kotlin/apply/ui/api/ApplicationFormRestControllerTest.kt
=> feat(application): block submitted application forms

frontend/src/components/form/BirthField.vue
=> fix(apply): modify birth field css

frontend/src/views/Recruits.vue
=> feat(apply): apply scrolling to the tab list

frontend/src/utils/validation/url.js
=> feat(apply): modify the url validation to include http or https

frontend/package-lock.json, frontend/package.json, frontend/src/components/BaseItem.vue, frontend/src/utils/date/index.js, frontend/src/views/ApplicationRegister.vue
=> fix(apply): modify to show server time

build.gradle.kts
=> feat(build): upgrade Kotlin 1.5.10 and Ktlint 10.1.0

src/main/kotlin/apply/application/ExcelService.kt
=> feat(excel): add the reference url to the applicant excel

build.gradle.kts, src/test/kotlin/apply/application/CheaterServiceTest.kt, src/test/kotlin/apply/application/EvaluationServiceTest.kt, src/test/kotlin/apply/application/EvaluationTargetServiceTest.kt, src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
=> refactor(test): migrate mockito to mockk

frontend/.storybook/preview.js, frontend/src/App.js, frontend/src/components/form/TextField/TextField.js, frontend/src/pages/Login.js, frontend/src/pages/Login/Login.js, frontend/src/pages/Login/Login.module.css, frontend/src/pages/Login/Login.stories.js
• 이메일,  비밀번호를 입력받는다.
- 이메일 : 이메일 형식 
- 비밀번호 : 영문, 숫자, 특수문자를 포함한 8~20자
- 로그인 성공시 token을 갱신하고, 홈페이지로 이동한다.
- 로그인 실패시 에러메시지를 alert로 보여준다.
=> refactor(apply): migrate login page component to react

frontend/.storybook/preview.js, frontend/src/App.js, frontend/src/pages/PasswordFindResult.js, frontend/src/pages/PasswordFindResult/PasswordFindResult.js, frontend/src/pages/PasswordFindResult/PasswordFindResult.module.css, frontend/src/pages/PasswordFindResult/PasswordFindResult.stories.js
- 사용자에게 임시 비밀번호가 발급된 email을 안내한다.
- 돌아가기 버튼을 이용하여 채용공고 확인(홈) 페이지로 돌아갈 수 있다.
=> refactor(apply): migrate password find result page component to react

frontend/src/App.js, frontend/src/components/ScrollToTop/ScrollToTop.js
- Scrool to top 컴포넌트 구현
- path가 변경될때마다 scroll을 왼쪽 상단 0,0 으로 이동합니다.
=> feat(apply): scroll to top when user move the page

src/main/kotlin/apply/application/ApplicantAuthenticationService.kt, src/main/kotlin/apply/domain/applicant/Applicant.kt, src/main/kotlin/apply/domain/authenticationcode/AuthenticationCode.kt, src/main/kotlin/apply/domain/authenticationcode/AuthenticationCodeRepository.kt, src/main/kotlin/apply/ui/api/ApplicantRestController.kt, src/main/resources/db/migration/V1_5__Separate_authentication_code.sql, src/test/kotlin/apply/ApplicantFixtures.kt, src/test/kotlin/apply/application/ApplicantAuthenticationServiceTest.kt, src/test/kotlin/apply/domain/authenticationcode/AuthenticationCodeRepositoryTest.kt, src/test/kotlin/apply/domain/authenticationcode/AuthenticationCodeTest.kt
=> feat(authentication): separate the authentication code

frontend/src/App.js, frontend/src/components/MainFooter/MainFooter.js, frontend/src/components/MainHeader/MainHeader.js, frontend/src/components/PrivateRoute/PrivateRoute.js, frontend/src/components/RecruitItem/RecruitItem.js, frontend/src/components/form/GenderField/GenderField.js, frontend/src/components/form/SummaryCheckField/SummaryCheckField.js, frontend/src/constants/messages.js, frontend/src/constants/path.js, frontend/src/constants/style.js, frontend/src/constants/tab.js, frontend/src/hooks/useFormContext.js, frontend/src/hooks/useRecruitmentContext.js, frontend/src/hooks/useTokenContext.js, frontend/src/pages/ApplicantRegister/ApplicantRegister.js, frontend/src/pages/ApplicationRegister/ApplicationRegister.js, frontend/src/pages/Login/Login.js, frontend/src/pages/PasswordEdit/PasswordEdit.js, frontend/src/pages/PasswordFind/PasswordFind.js, frontend/src/pages/PasswordFindResult/PasswordFindResult.js, frontend/src/pages/Recruits/Recruits.js, frontend/src/provider/FormProvider/InputField.js, frontend/src/provider/FormProvider/ResetButton.js, frontend/src/utils/date/index.js, frontend/src/utils/route/query.js
- 오류, 성공, 확인 메세지 상수화
- url path 상수화
Close #294
=> refactor(apply): constantize messages and paths

frontend/src/components/form/BirthField/BirthField.js, frontend/src/components/form/BirthField/BirthField.module.css
생년월일 입력창 개선했습니다. 
datalist 태그를 이용했습니다
[참고](https://developer.mozilla.org/ko/docs/Web/HTML/Element/Input#attr-list)
1. 추천리스트를 제공합니다.
2. 사용자입력에 따라 추천리스트가 추려집니다.
-  년: 2021 ~ 1972
- 월: 1 ~ 12
- 일: 1 ~ 31
=> feat(apply): improve the birthday input

frontend/.storybook/preview.js, frontend/src/components/form/BirthField/BirthField.js, frontend/src/components/form/TextInput/TextInput.module.css
- input 타입 text => number
- min, max 속성 설정
- 화살표 증감 버튼 css 숨김
이상입니다!
=> feat(apply): change the birthday input type

frontend/src/components/RecruitmentItem/RecruitmentItem.js
=> fix(apply): correct the import module path

frontend/src/App.js, frontend/src/assets/image/myPage.svg, frontend/src/components/@common/Button/Button.js, frontend/src/components/Header/Header.js, frontend/src/components/form/BirthField/BirthField.js, frontend/src/components/form/BirthField/BirthField.module.css, frontend/src/components/form/CancelButton/CancelButton.js, frontend/src/components/form/EmailField/EmailField.js, frontend/src/components/form/ResetButton/ResetButton.js, frontend/src/constants/path.js, frontend/src/pages/MyPage/MyPage.js, frontend/src/pages/MyPage/MyPage.module.css, frontend/src/pages/MyPage/MyPage.stories.js, frontend/src/pages/MyPageEdit/MyPageEdit.js, frontend/src/pages/MyPageEdit/MyPageEdit.module.css, frontend/src/pages/MyPageEdit/MyPageEdit.stories.js
=> feat(apply): Implement my page ui

src/main/kotlin/apply/application/AssignmentDtos.kt, src/main/kotlin/apply/application/AssignmentService.kt, src/main/kotlin/apply/domain/assignment/Assignment.kt, src/main/kotlin/apply/domain/assignment/AssignmentRepository.kt, src/main/kotlin/apply/ui/api/AssignmentRestController.kt, src/test/kotlin/apply/AssignmentFixtures.kt, src/test/kotlin/apply/application/AssignmentServiceTest.kt, src/test/kotlin/apply/application/MailTargetServiceTest.kt, src/test/kotlin/apply/ui/api/AssignmentRestControllerTest.kt
```
Patch : /api/recruitments/{recruitmentId}/missions/{missionId}/assignments
{
"githubUsername": "userName",
"pullRequestUrl": "url",
"note": "note"
}
```
close #344
=> feat(assignment): implement the function to modify assignment

src/main/kotlin/apply/ui/admin/BaseLayout.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentsFormView.kt
=> fix(apply): adjust the drawer style

src/main/kotlin/apply/domain/recruitment/RecruitmentPeriod.kt, src/main/kotlin/apply/ui/admin/cheater/CheaterFormDialog.kt, src/main/kotlin/apply/ui/admin/evaluation/EvaluationsFormView.kt, src/main/kotlin/apply/ui/admin/mission/MissionsFormView.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentsFormView.kt, src/main/kotlin/support/views/Buttons.kt, src/main/kotlin/support/views/Components.kt
=> feat(recruitment): handle recruitment save errors

src/main/kotlin/apply/ui/admin/mail/GroupMailTargetDialog.kt
Closes #459 
- 해당 내용은 버그가 아닌 것으로 판단하였습니다. 다만 사용상의 오해가 있을 수 있어 문구를 추가하였습니다.
=> feat(mail): add the reason to exclude unevaluated fallers

src/main/kotlin/apply/application/ApplicationFormDtos.kt, src/main/kotlin/apply/application/AssignmentDtos.kt, src/main/kotlin/apply/application/UserDtos.kt, src/main/kotlin/apply/domain/applicationform/ApplicationForm.kt, src/main/kotlin/apply/domain/assignment/Assignment.kt, src/main/kotlin/apply/domain/user/UserInformation.kt, src/main/resources/db/migration/V1_13__Modify_assignment_and_user_constraints.sql, src/test/kotlin/apply/domain/applicationform/ApplicationFormTest.kt, src/test/kotlin/apply/domain/user/UserRepositoryTest.kt
=> feat(apply): complement dto validation and constraints

frontend/src/components/form/EmailField/EmailField.js, frontend/src/hooks/useTimer.js
- 타이머 카운트시마다 현재 date를 기준으로 계산하도록 수정하였습니다. 
close #431
=> fix(apply): change the timer to count as a date now

src/main/kotlin/apply/application/RecruitmentDtos.kt, src/main/kotlin/apply/application/RecruitmentService.kt, src/main/kotlin/apply/application/TermDtos.kt, src/main/kotlin/apply/application/TermService.kt, src/main/kotlin/apply/domain/recruitment/RecruitmentRepository.kt, src/main/kotlin/apply/domain/term/TermRepository.kt, src/main/kotlin/apply/ui/admin/cheater/CheatersView.kt, src/main/kotlin/apply/ui/admin/evaluation/EvaluationsView.kt, src/main/kotlin/apply/ui/admin/mail/IndividualMailTargetDialog.kt, src/main/kotlin/apply/ui/admin/mail/MailForm.kt, src/main/kotlin/apply/ui/admin/mail/MailsView.kt, src/main/kotlin/apply/ui/admin/mission/MissionsView.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentForm.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentsFormView.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentsView.kt, src/main/kotlin/apply/ui/admin/selections/SelectionView.kt, src/main/kotlin/apply/ui/api/TermRestController.kt, src/test/kotlin/apply/RecruitmentFixtures.kt, src/test/kotlin/apply/application/TermServiceTest.kt, src/test/kotlin/apply/ui/api/TermRestControllerTest.kt
1. 기수를 생성, 수정, 삭제한다.
2. 존재하는 기수명으로 기수를 수정, 삭제할 수 없다.
3. 기수의 이름은 '단독 모집'일 수 없다.
4. 모집이 등록된 기수는 삭제할 수 없다.
close #380
=> feat(term): implement the term api

src/main/kotlin/apply/config/DatabaseInitializer.kt, src/main/kotlin/apply/config/Databases.kt, src/main/resources/application.properties
=> feat(apply): implement the database initializer

.gitignore, build.gradle.kts, src/docs/asciidoc/index.adoc
=> build(apply): set up gradle to apply rest docs

.platform/nginx/conf.d/elasticbeanstalk/01_admin-access.conf, build.gradle.kts, buildspec.yml, src/docs/asciidoc/index.adoc, src/test/kotlin/support/test/web/servlet/Servlets.kt
=> build(apply): prepare for release of api documentation

frontend/package.json, frontend/src/App.css, frontend/src/App.js, frontend/src/color.css, frontend/src/components/@common/Button/Button.module.css, frontend/src/components/@common/Radio/Radio.module.css, frontend/src/components/@common/TabItem/TabItem.module.css, frontend/src/components/@common/TabItem/TabItem.stories.tsx, frontend/src/components/@common/TabItem/TabItem.tsx, frontend/src/components/Footer/Footer.module.css, frontend/src/components/Header/Header.module.css, frontend/src/components/InquiryFloatingButton/InquiryFloatingButton.module.css, frontend/src/components/InquiryFloatingButton/InquiryFloatingButton.tsx, frontend/src/components/form/CheckBox/CheckBox.module.css, frontend/src/components/form/EmailField/EmailField.module.css, frontend/src/constants/tab.ts, frontend/src/constants/url.ts, frontend/src/mock/dummy.js, frontend/src/pages/Recruits/Recruits.js, frontend/src/pages/Recruits/Recruits.module.css, frontend/yarn.lock
Resolves #601 
- 현재 지원플랫폼에 존재하지 않는 문의하기 기능을 floating-button을 추가한다.
- global background color를 변경한다.
- 코스별로 필터링할수 있는 탭바 UI를 추가한다.
수정전
수정후
component에서 typescript를 이용할때 props의 타입을 interface혹은 인자에 인라인으로 줄때의 기준을 어떻게 할지에 대해서 여러분들의 의견이 궁금합니다!
디자인을 인프런의 문의하기를 바탕으로 임의로 해보았는데 디자인에 대한 의견이 궁금합니다!
필터링할수 있는 탭바에서 모바일일때 현재 없애는것만 구현하였는데 모바일에서 UI를 어떻게 할지 의견 부탁드립니다!
추가적으로 react-icons 사용했을때 cra에서 자동으로 tree-shaking을 해줘서 성능상 큰문제가 없는것 확인했습니다!
r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)
c: 웬만하면 반영해 주세요. (Comment)
=> feat(apply): add the contact us button and tab ui and change the background color

frontend/src/components/@common/StatusIndicator/StatusIndicator.module.css, frontend/src/components/InquiryFloatingButton/InquiryFloatingButton.module.css, frontend/src/components/RecruitmentItem/RecruitmentItem.module.css, frontend/src/pages/Recruits/Recruits.module.css
Resolves #663 
- 모바일 Safari에서 프로그램별 탭 선택 상태 표시가 깨지는 것을 해결한다.
- 모집 아이템(RecruitmentItem) UI에서 날짜 정보의 위치가 모집 이름의 길이에 따라 달라지는 것을 해결한다. 
- 플로팅 버튼(InquiryFloatingButton)이 화면 크기에 따라 이동하는 것을 해결한다. 
- 소개 글을 감싸는 박스(introduce-box)에 고정 높이를 하드코딩해서 해결하였습니다. 
- 반응형도 확인했습니다.
- grid을 이용해서 위치를 고정하였습니다. 
- 반응형도 확인했습니다.
데스크탑 화면
모바일 화면
- rem 단위에서 px 단위로 수정하였습니다. 
- 반응형도 확인했습니다. 
- 해결하려는 문제가 잘 수정되었는지 리뷰해주세요. 
- 반응형 UI를 잘 제공하는지 리뷰해주세요. 
- 현재의 컨벤션에서 개선되거나 수정할 만한 부분이 존재하는지 리뷰해주세요. 
---
=> fix(apply): modify the style of the recruitment list

buildspec.yml, src/main/resources/db/migration/V3_1__Modify_administrator.sql, src/main/resources/db/migration/V3_4__Assignment_note_longer.sql, src/main/resources/db/migration/V3__Create_judgment_tables_and_alter_administrator_table.sql
=> build(apply): set the time zone and prepare for deployment
