frontend/src/components/RecruitItem.vue, frontend/src/views/Recruits.vue
#79 번 PR의 커밋 로그 문제로 새로 브랜치를 파고 체리픽해서 다시 올립니다.
Resolves: #31
Resolves: #64
기존의 'recruitable'이었던 '모집 중' 상태가 'recruiting'으로 바뀌고
모집 예정을 'recruitable', 모집 일시 중지를 'unrecruitable'로 하였습니다.
모집 일시 중지 상태는 모집 중과 같은 탭에서 표시됩니다.
UI 디자인을 지원자 등록, 모집 폼 등과 어울리도록 수정했습니다.
=> feat(apply): implement recruitment list tab based on the recruitment status

src/main/kotlin/apply/application/EvaluationTargetService.kt, src/main/kotlin/apply/domain/evaluation/Evaluation.kt, src/main/kotlin/apply/domain/evaluationtarget/EvaluationAnswer.kt, src/main/kotlin/apply/domain/evaluationtarget/EvaluationAnswers.kt, src/main/kotlin/apply/domain/evaluationtarget/EvaluationStatus.kt, src/main/kotlin/apply/domain/evaluationtarget/EvaluationTarget.kt, src/main/kotlin/apply/domain/evaluationtarget/EvaluationTargetRepository.kt, src/test/kotlin/apply/application/EvaluationTargetServiceTest.kt, src/test/kotlin/apply/domain/evaluationitem/EvaluationItemRepositoryTest.kt, src/test/kotlin/apply/domain/evaluationtarget/EvaluationTargetRepositoryTest.kt
제이슨의 빛과 같은 리뷰 반영 01:26, 9/30
이렇게 코드가 바뀔 수 있군요. 리팩토링 재미있네요. 도와주신 제이슨 고마워요!
저는 처음에 생각했던 틀을 못 벗어났던 것 같습니다 😂
늦은 시간이라 머리가 맑지 않기에 내일 일어나서 추가적으로 손보도록 하겠습니다.
다들 굳나잇~
---
모든 리뷰 반영 21:30, 9/29
범의 조언에 힘입어 두가지 분기로 나눠봤습니다. 코멘트 땡큐!
그리고 기존 load 메서드는 저장하고 갱신하고 조회하여 반환까지 하는 무거운 메서드였습니다.
이를 한 메서드에서 최대한 하나의 일을 할 수 있도록 update라는 메서드로 수정했습니다. (save보다는 update가 낫다고 판단했습니다)
이제 불러오기 버튼이 눌리면 update를 실행한 후 findByEvaluationId 메서드를 호출해서 불러오는 방식을 취해야합니다.
실제 갱신 로직은 deleteAndSave라는 메서드에서 진행됩니다. 
---
resolve: #89 
복잡하고 중요도 높은 로직이고 저 혼자 구현했기에 상세한 리뷰 부탁드립니다..!!
허점이 있을게 분명해요🙃
구현은 아침에도 보여드렸듯 4가지 분기로 처리됩니다. 
알려드릴 사항이 있습니다.
1. 테스트 코드의 픽스쳐를 정리하지 못했습니다. 
`https://github.com/woowacourse/jwp-refactoring/pull/2#discussion_r491043437`를 보고나니 setUp으로 분리하기 힘든 여지가 많이 보여서 문맥에 맞추기 위해 각 메서드에 놔뒀습니다.
추후 메서드나 fixture 파일로 분리할 여지가 있습니다.
가독성을 위한 …
=> feat(evaluation): implement evaluation target and load function

src/main/kotlin/apply/application/ApplicantService.kt, src/main/kotlin/apply/application/ApplicationProperties.kt, src/main/kotlin/apply/application/CustomApplicationProperties.kt, src/main/kotlin/apply/application/MailService.kt, src/main/kotlin/apply/application/PasswordGenerator.kt, src/main/kotlin/apply/application/UUIDBasedPasswordGenerator.kt, src/main/kotlin/apply/domain/applicant/ApplicantRepository.kt, src/main/kotlin/apply/ui/api/ApplicantRestController.kt, src/main/kotlin/apply/ui/api/ApplicationFormRestController.kt, src/main/kotlin/apply/utils/RandomPasswordGenerator.kt, src/main/resources/application.properties, src/main/resources/templates/mail/password-reset.html, src/test/kotlin/apply/application/ApplicantServiceTest.kt
Resolves #119 
html 파일입니다.
MailSender -> JavaMailSender (메일전송시 html지원해줌)
css는 부득이하게 inline입니다
flex-column는 gmail-html에서 지원하지 않았습니다.
=> feat(apply): add a password reset email template

frontend/src/api/applicants.js, frontend/src/components/form/Form.vue, frontend/src/router/index.js, frontend/src/store/token.js, frontend/src/views/ApplicationRegister.vue, frontend/src/views/MyApplications.vue, frontend/src/views/PasswordEdit.vue, src/main/kotlin/apply/application/ApplicantDtos.kt, src/main/kotlin/apply/application/ApplicantService.kt, src/main/kotlin/apply/application/ApplicationFormDtos.kt, src/main/kotlin/apply/application/ApplicationFormService.kt, src/main/kotlin/apply/domain/applicant/Applicant.kt, src/main/kotlin/apply/ui/api/ApplicantRestController.kt, src/test/kotlin/apply/application/ApplicantServiceTest.kt, src/test/kotlin/apply/application/ApplicationFormServiceTest.kt, src/test/kotlin/apply/domain/applicant/ApplicantTest.kt, src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
Resolves #162 
- 지원서 수정, 작성시 이름과 비밀번호, 비밀번호 확인란을 지운다.
- 비밀번호를 수정할 수 있는 페이지를 따로 만든다.
---
이슈1 : 모바일로 전환하여 보면 이렇습니다.(비밀번호 수정 페이지만 해당)
이슈2 : #163 과 새로생긴 비밀번호 수정 버튼 위치 충돌 예상
=> feat(applicant): implement the password editing page

src/main/kotlin/apply/ui/admin/selections/SelectionView.kt
resolves #182 
프런트에서 관리자 화면을 출력하는 방식으로 수정했습니다.
백엔드에서 처리하는게 좋을까요?
백엔드에서 하면 지원서의 응답(`ApplicantForm#answers`)들과 모집항목(`RecruitmentItem`)들을 비교해서 현재 모집항목들에 맞게 만들어서 줄 것 같아요
공수가 클 거 같진 않은데, 항상 지원서 응답을 현재 모집항목과 싱크를 맞춰서 주는게 맞는지 고민이네요
=> fix(selection): modify the application so that it can be viewed when a recruitment item is added

frontend/src/App.css, frontend/src/App.js, frontend/src/components/MainFooter/MainFooter.js, frontend/src/components/MainHeader/MainHeader.js, frontend/src/components/PrivateRoute/PrivateRoute.js, frontend/src/hooks/useRecruitmentContext.js, frontend/src/hooks/useTokenContext.js, frontend/src/index.js, frontend/src/pages/ApplicantRegister.js, frontend/src/pages/ApplicationRegister.js, frontend/src/pages/Login.js, frontend/src/pages/PasswordEdit.js, frontend/src/pages/PasswordFind.js, frontend/src/pages/PasswordFindResult.js, frontend/src/pages/Recruits.js, frontend/src/provider/RecruitmentProvider.js, frontend/src/provider/TokenProvider.js
- 브랜과 페어로 진행했습니다.
- 라우팅 설정
- 로그인이 필요한 페이지에 접근 시 `alert` 후 로그인 페이지로 리다이렉트
- 기존 `vuex`로 관리되던 전역상태를 `ContextAPI`를 사용하도록 변경
- 백엔드 서버 api 응답(모집 목록)이 비어있는데, api 명세가 제공되거나 mock 데이터를 추가해주시면 개발에 큰 도움이 될 것 같습니다.
close #262
=> refactor(apply): migrate root component to react

frontend/src/constants/key.js, frontend/src/constants/messages.js, frontend/src/pages/ApplicationRegister/ApplicationRegister.js, frontend/src/provider/TokenProvider.js
- 로그인시 accessToken을 로컬스토리지에 저장
- 초기 App실행될 때 로컬스토리지에서 토큰 가져옴
- 지원서 작성 페이지에서는 createForm을 호출하는데, 이미 만들어진 경우라면 조회 api를 호출하도록 변경
- 이야기 해볼 거리
- 토큰 유효시간이 제한될 것인지
- 로컬스토리지에 저장하는것이 적절할지
관련 이슈: #44
=> feat(apply): change to keep logged in after refresh

frontend/src/constants/messages.js, frontend/src/hooks/useForm.js, frontend/src/provider/FormProvider/InputField.js
keyup 이벤트의 getModifierState 를 활용해서 CapsLock을 감지합니다.
이후 input하단의 에러메시지로 CapsLock이 켜진 상태임을 알립니다.
기존의 onChange 이벤트에서는 해당 메서드가 존재하지 않아서, keyUp이벤트를 감지하도록 input prop에 추가했습니다.
[참고 문서](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState)
브라우저 지원이 모디열키마다 들쑥날쑥인데 CapsLock은 전브라우저 다 지원합니당
=> feat(apply): implement password input capslock alert

src/main/kotlin/apply/domain/user/User.kt, src/test/kotlin/apply/domain/user/UserTest.kt
이슈 : 400 메시지에 kotlin.unit 문구가 노출
원인 : 
- 비밀번호 또는 사용자 정보 확인 시, 예외 메시지를 지정하지 않아 'Kotlin.unit' 문구가 직접 반환
작업 내용 : 
- 비밀번호 수정 시 잘못된 기존 비밀번호를 입력하는 경우 '비밀번호가 일치하지 않습니다.' 반환
- 비밀번호 초기화 시 잘못된 사용자 정보를 입력하는 경우 '사용자 정보가 일치하지 않습니다.' 반환
close #475
=> fix(user): add exception messages if user information does not match

frontend/src/App.css, frontend/src/components/Header/Header.module.css, frontend/src/components/form/CheckBox/CheckBox.module.css
- 간헐적으로 아이콘 깨짐
- 유니코드 문자 혹은 한글이 css content에 쓰인 경우, 브라우저 환경에 따라 깨져서 노출될 수 있습니다.
- 정확한 재현 스텝은 찾지 못했지만 테스트 중 꽤 자주 발견되어 수정해둡니다.
- CSS encoding 적용
- `::after` content 내용 유니코드로 변경
fix #454
=> fix(apply): encode css unicode contents

frontend/package.json, frontend/yarn.lock
- `yarn lint` 커맨드에서 prettier 가 적용되지 않은 경우도 검사. -> prettier 오류는 `error` 로 취급
- `yarn lint:fix` 커맨드 사용시 prettier 설정에 맞춰 autofix까지 포함
close #518
=> refactor(apply): add the prettier formatter to the lint command

src/main/kotlin/apply/application/RecruitmentService.kt, src/main/kotlin/apply/application/TermService.kt, src/main/kotlin/apply/ui/admin/BaseLayout.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentForm.kt, src/main/kotlin/apply/ui/admin/recruitment/RecruitmentsFormView.kt, src/main/kotlin/apply/ui/admin/term/TermForm.kt, src/main/kotlin/apply/ui/admin/term/TermFormDialog.kt, src/main/kotlin/apply/ui/admin/term/TermsView.kt, src/main/kotlin/support/views/Buttons.kt
Close #376 
+ 모집 생성 화면의 기수관리 버튼으로 접근
+ 기수 관리 화면 및 다이얼로그
+ RecruitmentService에 있던 `findAllTermSelectData()` TermService로 이동
+ TermsView에서 돌아가기 버튼 클릭시 다시 모집 생성 창으로 이동
+ 단독 모집은 DB에 존재하는 데이터가 아니고 디폴트 값이기 때문에 수정, 생성 버튼 비활성화
+ BindingIdentityFormLayout 사용
+ 추가되어야할 기능 TODO로 명시
=> feat(term): implement term management view

src/main/kotlin/apply/application/EvaluationDtos.kt, src/main/kotlin/apply/application/EvaluationService.kt, src/main/kotlin/apply/ui/admin/evaluation/EvaluationForm.kt, src/main/kotlin/apply/ui/admin/evaluation/EvaluationsView.kt, src/main/kotlin/apply/ui/admin/mail/GroupMailTargetDialog.kt, src/main/kotlin/apply/ui/admin/selections/SelectionView.kt, src/main/kotlin/apply/ui/api/EvaluationRestController.kt, src/main/kotlin/apply/ui/api/ExcelController.kt, src/test/kotlin/apply/application/EvaluationServiceTest.kt, src/test/kotlin/apply/ui/api/EvaluationRestControllerTest.kt
Resolves #580
- `이전 평가 없음`이라는 문자열이 평가(evaluation)와 관련된 코드에서 자주 반복되고 있었습니다. 또한, 관리자 페이지 화면에서는 보이지 않는데 View 코드에서는 더 많은 데이터를 가지고 있었습니다.
- `이전 평가 없음` 문자열을 `EvaluationDtos`에서 상수로 선언하여 사용하도록 변경하였습니다.
- 관리자 평가 페이지에서 보여주는 정보보다 View에서 응답으로 불필요하게 더 많은 데이터를 받지 않도록 평가와 관련된 service, dto, view의 코드를 전반적으로 리팩터링하였습니다.
- `EvaluationDtos`보다 상수화가 더 적합하다고 생각하는 위치가 있다면 알려주세요.
- 관리자 평가 페이지와 비교해서 사용되지 않는데 View 클래스에서 불필요하게 많은 데이터를 응답을 받는 경우가 있다면 알려주세요.
---
=> refactor(evaluation): refactor the code related to before evaluation

frontend/.prettierrc.json, frontend/src/components/@common/StatusIndicator/StatusIndicator.module.css, frontend/src/components/@common/StatusIndicator/StatusIndicator.stories.tsx, frontend/src/components/@common/StatusIndicator/StatusIndicator.tsx, frontend/src/components/RecruitmentItem/RecruitmentItem.js, frontend/src/components/RecruitmentItem/RecruitmentItem.module.css, frontend/src/components/RecruitmentItem/RecruitmentItem.stories.js, frontend/src/pages/Recruits/Recruits.js, frontend/src/pages/Recruits/Recruits.module.css, frontend/src/pages/Recruits/Recruits.stories.js, frontend/src/pages/SignUp/SignUp.stories.js, frontend/src/react-app-env.d.ts, frontend/types/css.d.ts
Resolves #600
figma를 참조하여 지원리스트의 스타일을 변경한다.
수정 전
수정 후
- 인디케이터의 상태
지원하기, 모집예정, 일시중지, 모집종료 -> 모집 중, 모집 예정
으로 줄이는게 맞을지? 줄인다면 onClick을 인디케이터가 아니라 ListItem에 줘야할지?
인디케이터를 button으로 했는데 윗 질문에 맞춰서 onClick이 ListItem에 위임 된다면 span이나 p로 하는게 맞을 것 같네요
- 대부분 rem으로 작성 돼 있어서 1rem=16px 기준으로 rem 변환하여 스타일하였습니다.
- figma에는 인디케이터가 사이즈가 다 다른데, 다 같은게 통일성이 있지 않을까 해서 일단은 동일하게 작성하였습니다. 의견 부탁드립니다.
- 모집상태별 탭(nav) 제거가 이슈에 있긴한데.. 코스별 탭 추가에서 재사용 가능 해 보이는데 삭제해야할지 궁금합니다.
코스별 탭 추가는 자스민 담당입니다.
r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)
c: 웬만하면 반영해 주세요. (Comment)
=> feat(apply): change the style of the recruitment list

frontend/src/components/@common/Container/Container.js, frontend/src/components/@common/Container/Container.module.css, frontend/src/pages/ApplicationRegister/ApplicationRegister.js, frontend/src/pages/AssignmentSubmit/AssignmentSubmit.js, frontend/src/pages/MyApplication/MyApplication.js, frontend/src/pages/MyPage/MyPage.module.css, frontend/src/pages/MyPageEdit/MyPageEdit.module.css, frontend/src/pages/PasswordEdit/PasswordEdit.js, frontend/src/pages/PasswordEdit/PasswordEdit.module.css, frontend/src/pages/SignUp/SignUp.js
Resolves #629 
- 메인 페이지와 다른 페이지의 공통 스타일을 맞춘다.
- Container의 box 스타일링 border를 제거했습니다.
- 적용 대상: 전체 페이지
- Container에 `titleAlign` prop을 추가하여 해당 prop 값에 따라 `h2` 태그의 className을 다르게 주는 방식으로 구현했습니다. prop의 default 값은 'center'로 줬습니다.
- 좌측 정렬 대상 페이지: 지원서 작성 페이지, 내 지원 현황 페이지, 과제 제출 페이지, 회원가입 페이지
- 중앙 정렬 대상 페이지: 로그인 페이지, 마이 페이지, 내 정보 수정 페이지, 비밀번호 변경 페이지
- 질문) 타이틀 폰트 사이즈는 피그마와 다른 상황입니다. border와 title 정렬에 대해서만 기존에 논의되어서 border와 title 정렬에 대해서만 작업했는데요. 기존 타이틀 폰트 사이즈를 유지할 것인지, 피그마에 적용된 사이즈로 변경할 것인지 논의가 필요합니다. 
- 타이틀 정렬을 적용하는 다른 방식이 있다면 제안해주세요.
- 피그마와 다른 부분이 없는지 함께 확인해주세요. 
(참고 - 배경색 변경은 [#601](https://github.com/woowacourse/service-apply/issues/601) 이슈에서 함께 진행합니다.)
---
=> feat(apply): unify the common style of all pages

frontend/src/pages/ApplicationRegister/ApplicationRegister.js, frontend/src/pages/ApplicationRegister/ApplicationRegister.module.css
Resolves #631 
- 지원서 작성 페이지를 개선한다. 
- 지원서 모집 페이지 상단에 있던 `RecruitmentItem`을 제거했습니다.
- `h3` 태그로 모집 타이틀 영역을 추가했습니다.
https://github.com/woowacourse/service-apply/issues/600 이슈의 작업으로 `RecruitmentItem`의 디자인이 달라졌습니다. 해당 작업이 아직 머지되지 않아서, 아래 캡쳐본은 수정된 디자인이 적용되지 않은 모습입니다.
- 피그마와 다른 부분이 없는지 확인해주세요.
- 질문) 피그마에 따라 작업했습니다만 개인적으로는 모집 타이틀이 너무 강조되지 않는 것 같아서, font-weight라도 조금 더 들어가는 게 좋지 않겠나 싶은데요. 다른 분들 의견 궁금합니다.
---
=> feat(apply): change the application form page ui

frontend/src/pages/ApplicationRegister/ApplicationRegister.js
Resolves #616 
- 포트폴리오 대신 증빙 자료로 문구를 변경한다.
- 아래와 같이 지원서의 URL 입력란 설명 문구를 변경했습니다.
[AS-IS] 자신을 드러낼 수 있는 개인 블로그, GitHub, 포트폴리오 주소 등이 있다면 입력해
주세요. 여러 개가 있는 경우 Notion, Google 문서 등을 사용하여 하나로 묶어 주세요.
[TO-BE] 작성한 몰입 경험과 관련된 개인 블로그, GitHub, 그 외 증빙 자료 등이 있다면 입력해주세요. 여러 개가 있는 경우 Notion이나 Google 문서 등을 사용하여 하나로 묶어 주세요. 링크를 공유하실 때에는 해당 링크가 공개 권한으로 접근 가능한지 확인해주세요.
- 설명 문구가 맞게 변경되었는지 확인해주세요.
---
=> feat(apply): change the description of the reference url

frontend/src/App.css, frontend/src/components/Header/Header.module.css, frontend/src/constants/tab.ts, frontend/src/hooks/useRecruitList.ts, frontend/src/hooks/useRecruitList.tsx, frontend/src/pages/Recruits/Recruits.js, frontend/src/pages/Recruits/Recruits.module.css
Resolves #630 
- 각 교육 프로그램에 대한 소개 문구를 추가한다.
- 모집 목록 상단에 교육 프로그램 소개 영역을 추가했습니다.
- `constants/tab.ts`의 `COURSE_TAB`에 교육 프로그램 설명 속성 `description` 추가했습니다. 기존에는 `courseTabStatus` 상태가 RECRUITS_TAB 프로퍼티 객체 하나의 label을 가지고 있었는데요. 이번에 `description`을 추가하면서 RECRUITS_TAB 중 하나의 프로퍼티 객체를 상태로 가지도록 변경했습니다.
- [#610](https://github.com/woowacourse/service-apply/pull/610)에서 논의한대로
- 모집 탭 영역 높이를 주어 스크롤 바와 탭 버튼이 겹치지 않도록 수정했습니다.
- 모집 탭 선택 상태와 필터링 된 모집 목록을 생성하는 useRecruitList를 분리했습니다.
- 프로그램 소개 영역의 컨텐츠가 탭에 종속적으로 변경되어서 `constants/tab.ts`의 `COURSE_TAB`에 프로그램 소개글을 추가하는 방식을 선택했습니다. 지금과 같은 방식 괜찮은지 의견 주세요.
- 새로운 파일을 만들 때 ts로 작성하는 규칙이 있는 것으로 알아서 useRecruitList를 .tsx로 작성했는데요. useReruitList 내부에서 사용하는 useRecruitmentContext의 경우 아직 마이그레이션 되지 않아, 이후 마이그레이션 작업이 진행되면 다시 수정이 필요할 수 있을 것 같습니다.
---
r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. …
=> feat(apply): add introduction of educational programs

frontend/public/index.html, frontend/src/components/MyApplicationItem/MyApplicationFormItem/MyApplicationFormItem.stories.tsx, frontend/src/constants/tab.ts, frontend/src/mock/dummy.ts
Resolves #665 
- 교육 프로그램 탭에서 `우아한테크캠프`를 제거한다.
- tab.ts에서 `우아한테크캠프`부분을 삭제하였습니다. 
- meta 태그(index.html)를 수정하였습니다. 
- dummy or storybook에서 `우아한테크캠프`부분을 다른 텍스트로 수정하였습니다. 
- 해결하려는 문제가 잘 수정되었는지 리뷰해주세요.
- 현재의 컨벤션에서 개선되거나 수정할 만한 부분이 존재하는지 리뷰해주세요.
---
=> feat(apply): remove some educational programs

frontend/src/components/@common/ModalWindow/ModalWindow.module.css, frontend/src/components/@common/Textarea/Textarea.module.css, frontend/src/components/Footer/Footer.module.css, frontend/src/components/Header/Header.module.css, frontend/src/components/MyApplicationItem/RecruitmentDetail/RecruitmentDetail.module.css, frontend/src/components/RecruitmentItem/RecruitmentItem.module.css, frontend/src/pages/MyApplication/MyApplication.module.css
Resolves #668, #632
- 내 지원 현황 페이지의 box가 모바일일 때에도 PC 기준 너비를 그대로 유지해 가로 스크롤이 생기고 있습니다. 
- 모집 목록 페이지에서 사용하는 컨테이너의 너비값과 동일하게 맞췄습니다. 
- 기존 스타일 규칙과 맞지 않는 부분이 있을까요?  
- 우디 PR에서 대부분의 모바일 breakpoint를 420px로 맞춰 동일하게 적용하였습니다. 좀 더 넓은 너비를 기준으로 해야 할 것 같다면 의견 부탁드려요. 
- https://github.com/woowacourse/service-apply/issues/632 이슈도 같이 해결되는지, 따로 확인이 필요할지 삼성 브라우저 소유자분들 확인 부탁드립니다!
-
---
=> fix(apply): add the media query to the style of the my application page
